# Generated by Django 4.1.6 on 2023-02-04 07:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_details',
            name='category',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_details',
            name='content',
            field=models.CharField(default='b', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_details',
            name='image',
            field=models.ImageField(default='c', upload_to='blog/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_details',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='blog_details',
            name='tags',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_details',
            name='title',
            field=models.CharField(default='f', max_length=500),
            preserve_default=False,
        ),
    ]
