# Generated by Django 4.1.6 on 2023-02-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_details_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_details',
            name='content',
        ),
    ]
