# Generated by Django 4.1.6 on 2023-02-06 07:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_details_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_details',
            name='content',
            field=ckeditor.fields.RichTextField(default='a'),
            preserve_default=False,
        ),
    ]
