# Generated by Django 4.1.6 on 2023-02-06 08:17

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_details_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_details',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
