# Generated by Django 4.1.6 on 2023-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolist',
            name='audio',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
