# Generated by Django 4.1.6 on 2023-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0002_audiolist_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolist',
            name='audio',
            field=models.FileField(upload_to='media/audio'),
        ),
        migrations.AlterField(
            model_name='audiolist',
            name='feature_image',
            field=models.ImageField(upload_to='media/feature_images'),
        ),
    ]
