# Generated by Django 4.1.6 on 2023-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0003_alter_audiolist_audio_alter_audiolist_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolist',
            name='audio',
            field=models.FileField(upload_to='media/audio/audiofile'),
        ),
        migrations.AlterField(
            model_name='audiolist',
            name='feature_image',
            field=models.ImageField(upload_to='media/audio/feature_images'),
        ),
    ]
