# Generated by Django 4.1.6 on 2023-02-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0004_alter_audiolist_audio_alter_audiolist_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiolist',
            old_name='feature_image',
            new_name='thumbnail',
        ),
    ]
