# Generated by Django 4.1.6 on 2023-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0005_rename_feature_image_audiolist_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolist',
            name='audio',
            field=models.FileField(upload_to='audio/audiofile'),
        ),
        migrations.AlterField(
            model_name='audiolist',
            name='thumbnail',
            field=models.ImageField(upload_to='audio/feature_images'),
        ),
    ]
