# Generated by Django 4.1.6 on 2023-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0006_alter_audiolist_audio_alter_audiolist_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiolist',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='audiolist',
            name='content',
        ),
        migrations.RemoveField(
            model_name='audiolist',
            name='tags',
        ),
        migrations.AddField(
            model_name='audiolist',
            name='discription',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
