# Generated by Django 4.1.6 on 2023-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0007_remove_audiolist_catagory_remove_audiolist_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolist',
            name='date_time',
            field=models.DateTimeField(default='2006-10-25 14:30:59', editable=False),
            preserve_default=False,
        ),
    ]
