# Generated by Django 4.1.6 on 2023-02-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0008_audiolist_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolist',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
