# Generated by Django 4.1.6 on 2023-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofile', '0009_alter_audiolist_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolist',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
